name: CI

on: [push]

jobs:
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Set node version'
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: 'Install dependencies'
        run: yarn install --frozen-lockfile

      - name: 'Lint'
        run: yarn lint

  test:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Set node version'
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: 'Install dependencies'
        run: yarn install --frozen-lockfile

      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps

      - name: Run integration tests
        run: yarn test:integration
        env:
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          VERCEL_URL: ${{ secrets.VERCEL_URL }}
          CAPTACHA_API_KEY: ${{ secrets.CAPTACHA_API_KEY }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          HOST_URL: 'http://127.0.0.1:5173'
          TELEGRAM_API_TOKEN: 'invalid_token'
          TELEGRAM_CHAT_ID: '012345'

  telegram-notification:
    runs-on: ubuntu-latest
    needs: [test, lint]
    if: ${{ always() && contains(join(needs.*.result, ','), 'failure') }}
    steps:
      - name: 'Telegram Notification'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_API_TOKEN }}
          message: |
            ⚠️ Pipeline failed
            Repository: ${{ github.repository }}
