name: e2e Tests

on:
  deployment_status:
jobs:
  run-e2es:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install && yarn playwright install --with-deps chromium

      - name: Run tests
        run: yarn test:integration
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ github.event.deployment_status.environment_url }}
          CI: true

      - name: 'Upload screenshots'
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-screenshots
          path: test-results/*
          retention-days: 30
